apiVersion: apps/v1
kind: Deployment
metadata:
  name: poxy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poxy-app
  template:
    metadata:
      labels:
        app: poxy-app
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: okteto/poxy-app:java-maven
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: poxy-app
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: poxy-app
spec:
  type: ClusterIP
  ports:
    - name: poxy-app
      port: 8080
  selector:
    app: poxy-app
