apiVersion: apps/v1
kind: Deployment
metadata:
  name: @project.artifactId@
spec:
  replicas: 1
  selector:
    matchLabels:
      app: @project.artifactId@
  template:
    metadata:
      labels:
        app: @project.artifactId@
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: @docker.registry@/@project.artifactId@:@project.version@
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: @project.artifactId@
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: @project.artifactId@
spec:
  type: ClusterIP
  ports:
    - name: @project.artifactId@
      port: 8080
  selector:
    app: @project.artifactId@
